// Generated by scripts/generate-build-metadata.mjs. Do not edit.

export const GENERATED_BUILD_METADATA = Object.freeze({
  schemaVersion: 1,
  version: "0.0.0",
  buildId: "development",
  channel: "development",
} as const);
